apiVersion: v2
name: lifecycle-controller
description: A Kubernetes controller to manage the lifecycle of standard resources through time-based annotations.
type: application
version: 0.2.1
appVersion: "v0.2.1"
keywords:
  - kubernetes
  - controller
  - operator
  - lifecycle
home: https://github.com/cstanislawski/lifecycle-controller
sources:
  - https://github.com/cstanislawski/lifecycle-controller
maintainers:
  - name: cstanislawski
