name: Verify Helm Chart

on:
  push:
    paths:
      - 'charts/**'
      - 'Makefile'
  pull_request:
    paths:
      - 'charts/**'
      - 'Makefile'

env:
  HELM_CHART_PATH: charts/lifecycle-controller

jobs:
  test-lint:
    name: Lint and Template Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Get helm version from file
        id: get-helm-version
        run: |
          echo "version=$(head ${{ env.HELM_CHART_PATH }}/.Version)" >> $GITHUB_OUTPUT

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ steps.get-helm-version.outputs.version }}

      - name: Running Helm Lint
        run: make helm-lint HELM_CHART_PATH=${{ env.HELM_CHART_PATH }}

      - name: Running Helm Template Validation
        run: make helm-template HELM_CHART_PATH=${{ env.HELM_CHART_PATH }}
