name: Test Helm Chart

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'charts/**'
      - 'Makefile'
      - '.github/workflows/test-helm.yml'

permissions: {}

env:
  HELM_CHART_PATH: charts/lifecycle-controller

jobs:
  template-test:
    permissions:
      contents: read
    name: Helm template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Read Helm version from .Version
        id: get-helm-version
        run: |
          echo "version=$(head ${{ env.HELM_CHART_PATH }}/.Version)" >> $GITHUB_OUTPUT

      - uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5
        with:
          version: ${{ steps.get-helm-version.outputs.version }}

      - run: helm version

      - name: Validate Helm templates
        run: make helm-template HELM_CHART_PATH=${{ env.HELM_CHART_PATH }}
