name: Helm E2E Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'charts/**'
      - 'test/e2e-helm/**'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/test-e2e-helm.yml'

env:
  HELM_CHART_PATH: charts/lifecycle-controller

jobs:
  test-e2e-helm:
    name: Helm E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod

      - run: go version

      - name: Read Helm version from .Version
        id: get-helm-version
        run: |
          echo "version=$(head ${{ env.HELM_CHART_PATH }}/.Version)" >> $GITHUB_OUTPUT

      - uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5
        with:
          version: ${{ steps.get-helm-version.outputs.version }}

      - run: helm version

      - name: Install latest kind release
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Run Helm E2E tests
        run: |
          make test-e2e-helm
