name: Helm Unit Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'charts/**'
      - 'Makefile'
      - '.github/workflows/test-helm-unittest.yml'

env:
  HELM_CHART_PATH: charts/lifecycle-controller

jobs:
  helm-unittest:
    name: Helm unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Read Helm version from .Version
        id: get-helm-version
        run: |
          echo "version=$(head ${{ env.HELM_CHART_PATH }}/.Version)" >> $GITHUB_OUTPUT

      - uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5
        with:
          version: ${{ steps.get-helm-version.outputs.version }}

      - run: helm version

      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest --verify=false

      - name: Run Helm unit tests
        run: make helm-unittest HELM_CHART_PATH=${{ env.HELM_CHART_PATH }}
