name: Helm Unit Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'charts/**'
      - 'Makefile'
      - '.github/workflows/test-helm-unittest.yml'

env:
  HELM_CHART_PATH: charts/lifecycle-controller

jobs:
  helm-unittest:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Get helm version from file
        id: get-helm-version
        run: |
          echo "version=$(head ${{ env.HELM_CHART_PATH }}/.Version)" >> $GITHUB_OUTPUT

      - name: Set up Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5
        with:
          version: ${{ steps.get-helm-version.outputs.version }}

      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest --verify=false

      - name: Running Helm Unit Tests
        run: make helm-unittest HELM_CHART_PATH=${{ env.HELM_CHART_PATH }}
